# Generated by Django 3.0.3 on 2020-04-07 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('date', models.DateTimeField(help_text='YYYY-MM-DD')),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='image')),
            ],
        ),
    ]
