# Generated by Django 3.0.3 on 2020-07-08 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='note',
            name='due_date',
            field=models.DateField(default='2020-07-08'),
        ),
        migrations.AlterField(
            model_name='note',
            name='date',
            field=models.DateField(default='2020-07-08'),
        ),
    ]
